apiVersion: v1
kind: Secret
metadata:
  namespace: prow
  name: s3-credentials
stringData:
  service-account.json: |
    {
      "region": "minio",
      "access_key": "$AZURE_STORAGE_ACCOUNT_USER",
      "endpoint": "https://minio.prow.svc.cluster.local",
      "insecure": true,
      "s3_force_path_style": true,
      "secret_key": "$AZURE_STORAGE_ACCOUNT_PASSWORD"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: prow
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      nodeSelector:
        agentpool: prow
      initContainers:
      - name: generate-tls
        image: alpine/openssl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          openssl req -x509 -nodes -days 3650 \
            -newkey rsa:2048 \
            -keyout /certs/private.key \
            -out /certs/public.crt \
            -subj "/CN=minio.prow.svc.cluster.local" \
            -addext "subjectAltName=DNS:minio,DNS:minio.prow,DNS:minio.prow.svc,DNS:minio.prow.svc.cluster.local"
        volumeMounts:
        - name: tls-certs
          mountPath: /certs
      containers:
      - name: minio
        image: minio/minio:RELEASE.2022-10-24T18-35-07Z
        args:
        - gateway
        - azure
        - --console-address=0.0.0.0:$MINIO_CONSOLE_PORT
        env:
        - name: MINIO_ROOT_USER
          value: "$AZURE_STORAGE_ACCOUNT_USER"
        - name: MINIO_ROOT_PASSWORD
          value: "$AZURE_STORAGE_ACCOUNT_PASSWORD"
        - name: MINIO_REGION_NAME
          value: minio
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
            scheme: HTTPS
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
            scheme: HTTPS
        volumeMounts:
        - name: tls-certs
          mountPath: /root/.minio/certs
      volumes:
      - name: tls-certs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: prow
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 9000
    protocol: TCP
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: prow
spec:
  type: NodePort
  ports:
  - port: $MINIO_CONSOLE_PORT
    targetPort: $MINIO_CONSOLE_PORT
    protocol: TCP
  selector:
    app: minio
