apiVersion: v1
data:
  # referenced by a lots of official k8s jobs, this is a fake secret to bypass the mount phase
  service-account.json: $(FAKE_MOUNT_SECRET)
kind: Secret
metadata:
  name: service-account
  namespace: prow
type: Opaque