periodics:
- interval: 24h
  agent: kubernetes
  name: echo-test
  namespace: test-pods
  spec:
    containers:
      - image: alpine
        command: ["/bin/date"]
postsubmits: {}
presubmits:
  $GITHUB_ORG/$GITHUB_REPO:
  - always_run: true
    branches:
    - release-1.24-lts
    context: pull-kubernetes-verify-govet-levee
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-service-account: "true"
    name: pull-kubernetes-verify-govet-levee
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - args:
        - verify
        command:
        - make
        env:
        - name: WHAT
          value: govet-levee
        - name: EXCLUDE_TYPECHECK
          value: "y"
        - name: EXCLUDE_FILES_REMAKE
          value: "y"
        - name: EXCLUDE_GODEP
          value: "y"
        - name: KUBE_VERIFY_GIT_BRANCH
          value: release-1.24
        - name: REPO_DIR
          value: /workspace/k8s.io/kubernetes
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        imagePullPolicy: IfNotPresent
        name: ""
        resources:
          limits:
            cpu: "7"
            memory: 12Gi
          requests:
            cpu: "7"
            memory: 12Gi
        securityContext:
          privileged: true
  - always_run: true
    branches:
    - release-1.24-lts
    context: pull-kubernetes-dependencies
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-service-account: "true"
    name: pull-kubernetes-dependencies
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - args:
        - make
        - verify
        command:
        - runner.sh
        env:
        - name: WHAT
          value: external-dependencies-version vendor vendor-licenses
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        name: main
        resources:
          limits:
            cpu: "2"
            memory: 1288490188800m
          requests:
            cpu: "2"
            memory: 1288490188800m
        securityContext:
          privileged: true
  - always_run: true
    branches:
    - release-1.24-lts
    context: pull-kubernetes-integration
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-service-account: "true"
    name: pull-kubernetes-integration
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - args:
        - ./hack/jenkins/test-dockerized.sh
        command:
        - runner.sh
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        name: ""
        resources:
          limits:
            cpu: "6"
            memory: 15Gi
          requests:
            cpu: "6"
            memory: 15Gi
        securityContext:
          privileged: true
  - always_run: true
    annotations:
      description: run with GO_VERSION set to the original go version used for this branch
    branches:
    - release-1.24-lts
    context: pull-kubernetes-integration-go-compatibility
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-service-account: "true"
    name: pull-kubernetes-integration-go-compatibility
    optional: true
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - args:
        - ./hack/jenkins/test-dockerized.sh
        command:
        - runner.sh
        env:
        - name: GO_VERSION
          value: 1.19.1
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        name: ""
        resources:
          limits:
            cpu: "6"
            memory: 15Gi
          requests:
            cpu: "6"
            memory: 15Gi
        securityContext:
          privileged: true
  - always_run: true
    branches:
    - release-1.24-lts
    context: pull-kubernetes-unit
    decorate: true
    labels:
      preset-service-account: "true"
    name: pull-kubernetes-unit
    path_alias: k8s.io/kubernetes
    spec:
      nodeSelector:
        agentpool: k8stest
      containers:
      - command:
        - make
        - test
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        name: ""
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 4Gi
      securityContext:
        runAsUser: 2000
  - always_run: true
    annotations:
      description: run with GO_VERSION set to the original go version used for this branch
    branches:
    - release-1.24-lts
    context: pull-kubernetes-unit-go-compatibility
    decorate: true
    labels:
      preset-service-account: "true"
    name: pull-kubernetes-unit-go-compatibility
    optional: true
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - command:
        - make
        - test
        env:
        - name: GO_VERSION
          value: 1.19.1
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        name: ""
        resources:
          limits:
            cpu: "4"
            memory: 36Gi
          requests:
            cpu: "4"
            memory: 36Gi
      securityContext:
        runAsUser: 2000
  - always_run: true
    branches:
    - release-1.24-lts
    context: pull-kubernetes-typecheck
    decorate: true
    name: pull-kubernetes-typecheck
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - args:
        - verify
        command:
        - make
        env:
        - name: WHAT
          value: typecheck typecheck-providerless
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        name: main
        resources:
          limits:
            cpu: "5"
            memory: 32Gi
          requests:
            cpu: "5"
            memory: 32Gi