# 1.30-lts jobs, do not change indentation of the lines below, it need to be aligned with base.yaml
# Based on config/jobs/kubernetes/sig-release/release-branch-jobs/1.30.yaml
  - always_run: false
    branches:
    - release-1.30-lts
    context: pull-kubernetes-conformance-kind-ipv6-parallel
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-service-account: "true"
    max_concurrency: 8
    name: pull-kubernetes-conformance-kind-ipv6-parallel
    optional: true
    path_alias: k8s.io/kubernetes
    run_if_changed: ^test/
    spec:
      containers:
      - command:
        - wrapper.sh
        - bash
        - -c
        - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
        env:
        - name: DOCKER_IN_DOCKER_IPV6_ENABLED
          value: "true"
        - name: IP_FAMILY
          value: ipv6
        - name: PARALLEL
          value: "true"
        image: gcr.io/k8s-staging-test-infra/krte:v20250714-70266d743a-1.30
        name: ""
        resources:
          limits:
            cpu: "4"
            memory: 9000Mi
          requests:
            cpu: "4"
            memory: 9000Mi
        securityContext:
          privileged: true
  - always_run: true
    branches:
    - release-1.30-lts
    context: pull-kubernetes-dependencies
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-service-account: "true"
    name: pull-kubernetes-dependencies
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - args:
        - make
        - verify
        command:
        - runner.sh
        env:
        - name: WHAT
          value: external-dependencies-version vendor vendor-licenses
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20250714-70266d743a-1.30
        name: main
        resources:
          limits:
            cpu: "2"
            memory: 1288490188800m
          requests:
            cpu: "2"
            memory: 1288490188800m
        securityContext:
          privileged: true
  - always_run: true
    branches:
    - release-1.30-lts
    context: pull-kubernetes-integration
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-service-account: "true"
    name: pull-kubernetes-integration
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - args:
        - ./hack/jenkins/test-dockerized.sh
        command:
        - runner.sh
        env:
        - name: KUBE_INTEGRATION_TEST_MAX_CONCURRENCY
          value: "8"
        - name: KUBE_TIMEOUT
          value: -timeout=1h30m
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20250714-70266d743a-1.30
        name: ""
        resources:
          limits:
            cpu: "8"
            memory: 20Gi
          requests:
            cpu: "8"
            memory: 20Gi
        securityContext:
          privileged: true
  - always_run: true
    branches:
    - release-1.30-lts
    context: pull-kubernetes-integration-go-compatibility
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-service-account: "true"
    name: pull-kubernetes-integration-go-compatibility
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - args:
        - ./hack/jenkins/test-dockerized.sh
        command:
        - runner.sh
        env:
        - name: GO_VERSION
          value: 1.22.1
        - name: KUBE_HACK_TOOLS_GOTOOLCHAIN
          value: auto
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20250714-70266d743a-1.30
        name: ""
        resources:
          limits:
            cpu: "6"
            memory: 15Gi
          requests:
            cpu: "6"
            memory: 15Gi
        securityContext:
          privileged: true
  - always_run: true
    branches:
    - release-1.30-lts
    context: pull-kubernetes-e2e-kind
    decorate: true
    decoration_config:
      grace_period: 15m0s
      timeout: 1h0m0s
    labels:
      preset-dind-enabled: "true"
    name: pull-kubernetes-e2e-kind
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - command:
        - wrapper.sh
        - bash
        - -c
        - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
        env:
        - name: FOCUS
          value: .
        - name: SKIP
          value: \[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|PodSecurityPolicy|LoadBalancer|load.balancer|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing|NFS|nfs|inline.execution.and.attach|should.be.rejected.when.no.endpoints.exist
        - name: PARALLEL
          value: "true"
        image: gcr.io/k8s-staging-test-infra/krte:v20250714-70266d743a-1.30
        name: ""
        resources:
          limits:
            cpu: "7"
            memory: 9000Mi
          requests:
            cpu: "7"
            memory: 9000Mi
        securityContext:
          privileged: true
  - always_run: true
    branches:
    - release-1.30-lts
    context: pull-kubernetes-e2e-kind-ipv6
    decorate: true
    decoration_config:
      grace_period: 15m0s
      timeout: 1h0m0s
    labels:
      preset-dind-enabled: "true"
    name: pull-kubernetes-e2e-kind-ipv6
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - command:
        - wrapper.sh
        - bash
        - -c
        - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
        env:
        - name: FOCUS
          value: .
        - name: SKIP
          value: \[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[sig-storage\]|PodSecurityPolicy|LoadBalancer|load.balancer|In-tree.Volumes.\[Driver:.nfs\]|PersistentVolumes.NFS|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing
        - name: PARALLEL
          value: "true"
        - name: DOCKER_IN_DOCKER_IPV6_ENABLED
          value: "true"
        - name: IP_FAMILY
          value: ipv6
        image: gcr.io/k8s-staging-test-infra/krte:v20250714-70266d743a-1.30
        name: ""
        resources:
          limits:
            cpu: "4"
            memory: 9Gi
          requests:
            cpu: "4"
            memory: 9Gi
        securityContext:
          privileged: true
  - always_run: true
    branches:
    - release-1.30-lts
    context: pull-kubernetes-conformance-kind-ga-only-parallel
    decorate: true
    decoration_config:
      grace_period: 15m0s
      timeout: 1h0m0s
    labels:
      preset-dind-enabled: "true"
    name: pull-kubernetes-conformance-kind-ga-only-parallel
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - command:
        - wrapper.sh
        - bash
        - -c
        - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
        env:
        - name: GA_ONLY
          value: "true"
        - name: PARALLEL
          value: "true"
        image: gcr.io/k8s-staging-test-infra/krte:v20250714-70266d743a-1.30
        name: ""
        resources:
          limits:
            cpu: "4"
            memory: 9Gi
          requests:
            cpu: "4"
            memory: 9Gi
        securityContext:
          privileged: true
  - always_run: true
    branches:
    - release-1.30-lts
    context: pull-kubernetes-unit
    decorate: true
    labels:
      preset-service-account: "true"
    name: pull-kubernetes-unit
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - command:
        - make
        - test
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20250714-70266d743a-1.30
        name: ""
        resources:
          limits:
            cpu: "4"
            memory: 36Gi
          requests:
            cpu: "4"
            memory: 36Gi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsGroup: 2010
        runAsUser: 2001
  - always_run: true
    branches:
    - release-1.30-lts
    context: pull-kubernetes-unit-go-compatibility
    decorate: true
    labels:
      preset-service-account: "true"
    name: pull-kubernetes-unit-go-compatibility
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - command:
        - make
        - test
        env:
        - name: GO_VERSION
          value: 1.22.1
        - name: KUBE_HACK_TOOLS_GOTOOLCHAIN
          value: auto
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20250714-70266d743a-1.30
        name: ""
        resources:
          limits:
            cpu: "4"
            memory: 36Gi
          requests:
            cpu: "4"
            memory: 36Gi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsGroup: 2010
        runAsUser: 2001
  - always_run: true
    branches:
    - release-1.30-lts
    context: pull-kubernetes-typecheck
    decorate: true
    name: pull-kubernetes-typecheck
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - args:
        - verify
        command:
        - make
        env:
        - name: WHAT
          value: typecheck typecheck-providerless
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20250714-70266d743a-1.30
        name: main
        resources:
          limits:
            cpu: "5"
            memory: 32Gi
          requests:
            cpu: "5"
            memory: 32Gi
  - always_run: false
    branches:
    - release-1.30-lts
    context: pull-kubernetes-update
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-service-account: "true"
    name: pull-kubernetes-update
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - args:
        - ./hack/jenkins/update-dockerized.sh
        command:
        - runner.sh
        env:
        - name: EXCLUDE_TYPECHECK
          value: "y"
        - name: EXCLUDE_GODEP
          value: "y"
        - name: KUBE_VERIFY_GIT_BRANCH
          value: release-1.30-lts
        - name: REPO_DIR
          value: /workspace/k8s.io/kubernetes
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20250714-70266d743a-1.30
        imagePullPolicy: Always
        name: ""
        resources:
          limits:
            cpu: "7"
            memory: 12Gi
          requests:
            cpu: "7"
            memory: 12Gi
        securityContext:
          privileged: true
  - always_run: true
    branches:
    - release-1.30-lts
    context: pull-kubernetes-verify
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-service-account: "true"
    name: pull-kubernetes-verify
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - args:
        - ./hack/jenkins/verify-dockerized.sh
        command:
        - runner.sh
        env:
        - name: EXCLUDE_TYPECHECK
          value: "y"
        - name: EXCLUDE_GODEP
          value: "y"
        - name: KUBE_VERIFY_GIT_BRANCH
          value: release-1.30-lts
        - name: REPO_DIR
          value: /workspace/k8s.io/kubernetes
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20250714-70266d743a-1.30
        imagePullPolicy: Always
        name: ""
        resources:
          limits:
            cpu: "7"
            memory: 12Gi
          requests:
            cpu: "7"
            memory: 12Gi
        securityContext:
          privileged: true
  - always_run: true
    branches:
    - release-1.30-lts
    context: pull-kubernetes-linter-hints
    decorate: true
    name: pull-kubernetes-linter-hints
    optional: true
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - args:
        - verify
        - WHAT=golangci-lint-pr-hints
        command:
        - make
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20250714-70266d743a-1.30
        name: ""
        resources:
          limits:
            cpu: "5"
            memory: 12Gi
          requests:
            cpu: "5"
            memory: 12Gi
