apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: prowdata
  namespace: minio4prow
scheduler:
  name: ""
spec:
  configuration:
    name: prowdata-env-configuration
  credsSecret:
    name: prowdata-secret
  exposeServices: {}
  features: {}
  image: minio/minio:RELEASE.2024-07-13T01-46-15Z
  imagePullSecret:
    name: ""
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - prowdata
            - key: v1.min.io/pool
              operator: In
              values:
              - pool-0
          topologyKey: kubernetes.io/hostname
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
      seccompProfile:
        type: RuntimeDefault
    name: pool-0
    resources:
      requests:
        cpu: "2"
        memory: 5Gi
    runtimeClassName: ""
    securityContext:
      fsGroup: 0
      fsGroupChangePolicy: Always
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    servers: 2
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "274877906944"
        storageClassName: prowdata
      status: {}
    volumesPerServer: 2
  requestAutoCert: false
  users:
  - name: prowdata-user-0
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    v1.min.io/tenant: prowdata
  name: prowdata-env-configuration
  namespace: minio4prow
data:
  config.env: |
    export MINIO_ROOT_USER=""
    export MINIO_ROOT_PASSWORD=""
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    v1.min.io/tenant: prowdata
  name: prowdata-secret
  namespace: minio4prow
type: Opaque
data:
  accesskey: ""
  secretkey: ""
immutable: true
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    v1.min.io/tenant: prowdata
  name: prowdata-user-0
  namespace: minio4prow
type: Opaque
immutable: true
data:
  CONSOLE_ACCESS_KEY: 
  CONSOLE_SECRET_KEY: 
