name: Deploy AKS LTS Prow PRTest
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy-aks-lts-prow-PRTest:
    uses: ./.github/workflows/deploy-lts-prow.yaml
    with:
      deployEnv: PRTest